name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12
      
      - name: install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: cd test
            export PYTHONPATH=$(pwd):$PYTHONPATH
            python3 -m unittest -k test
      